### PR TITLE
Create utime.h

### PR DESCRIPTION
**Pull request by bucanero**
Add utime() definition.

As mentioned in https://github.com/ps3dev/PSL1GHT/pull/82 , this is a patch to add the missing definition.

### CODE REVIEW

**Review by miigotu — CHANGES_REQUESTED** [review]
"which will then replace the stub in `newlib/libc/include/sys/utime.h` (which defines the `struct utimbuf` but no function prototypes)"

You need to remove the stub

**Comment by bucanero** [comment]
> You need to remove the stub

thanks 😄 stub file removed

**Comment by zeldin** [comment]
> You need to remove the stub

What??  No!    The stub header explicitly says
```
If there is a utime.h in libc/sys/SYSDIR/sys,
   it will override this one.  
```
So since it is overridden it does  _not_ need removing.  (If that were the case modifying the stub would have been better...)

**Comment by zeldin** [comment]
I have now cherry-picked the first commit and regenerated the patch.  Closing this PR.

**Comment by miigotu** [comment]
My bad lol I didnt look at the stub. =P

**Pull request closed without merging**
